import { QueryProvider } from "@/shared";
import "@mantine/core/styles.css";
import "@mantine/notifications/styles.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { LanguageProvider } from "@/features/translation";
import {
    ColorSchemeScript,
    MantineProvider,
    createTheme,
    mantineHtmlProps,
} from "@mantine/core";
import { ModalsProvider } from "@mantine/modals";
import { Notifications } from "@mantine/notifications";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const theme = createTheme({
    autoContrast: true,
    fontFamily: "Geist",
    fontFamilyMonospace: "Geist Mono",
    fontSmoothing: true,
    defaultRadius: "md",
    primaryColor: "indigo",
    respectReducedMotion: true,
    luminanceThreshold: 0.3,
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" {...mantineHtmlProps}>
            <head>
                <ColorSchemeScript />
            </head>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <LanguageProvider>
                    <QueryProvider>
                        <MantineProvider
                            theme={theme}
                            withCssVariables
                            classNamesPrefix="theeka"
                        >
                            <ModalsProvider>{children}</ModalsProvider>
                            <Notifications />
                        </MantineProvider>
                    </QueryProvider>
                </LanguageProvider>
            </body>
        </html>
    );
}
