import { LanguageProvider } from "@/features/translation";
import { QueryProvider } from "@/shared";
import { Toaster } from "@/shared/components/ui/sonner";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import React from "react";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body
                className={` ${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <LanguageProvider>
                    <QueryProvider>
                        {children}

                        <Toaster richColors />
                    </QueryProvider>
                </LanguageProvider>
                <Script
                    src="https://unpkg.com/@material-tailwind/html@latest/scripts/ripple.js"
                    async
                />
            </body>
        </html>
    );
}
